Update location api endpoint
codersagainstcovidorg/covid19testing-backend pull request #8
Opened 2020-04-04 21:11 UTC by iloveicedgreentea

2020-04-04 21:51 UTC, jorge-caballero requested changes
- [ ] update the `updated_on` field when a `PUT` request succeeds

2020-04-04 21:51 UTC, jorge-caballero commented on application/database/database_routes.py
>    """
@iloveicedgreentea i may be missing it, but the code does not update the `updated_on` field when a `PUT` request succeeds

2020-04-04 23:55 UTC, iloveicedgreentea commented
Fixed some minor things, added automatic migrations

2020-04-05 00:45 UTC, jorge-caballero approved these changes
LGTM, but honestly not the best to review migrations written in python...it's been little while since I've been in that mode.

2020-04-05 03:00 UTC, jorge-caballero approved these changes
LGTM.

2020-04-12 00:23 UTC, merged